### PR TITLE
main: Add subdirs for UBports

### PR DESCRIPTION
**Pull request by fredldotme**
This adds:
- droidmedia for libminisf
- audioflingerglue for certain devices
- libhybris & platform-api for sensor support

The components to be built have to be specified
in the device configuration makefiles.

### CODE REVIEW

**Comment by Vince1171** [comment]
Shouldn't you also add those repos in the manifest?
https://github.com/Halium/android

**Comment by fredldotme** [comment]
It's on the list, yes. I'll provide the necessary pull request ASAP.

**Comment by NotKit** [comment]
Should be good to merge after default.xml changes are merged.

**Comment by Vince1171** [comment]
> Should be good to merge after default.xml changes are merged.

Done

**Pull request merged**
